# -*- coding: utf-8 -*-
"""Untitled106.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12F9yNN_B4j4DDCoRoIG1IsY5FqyTMXEB
"""

import numpy as np
import matplotlib.pyplot as plt


# define a sample "ODE" as an input for euler method
def example_ODE(t, y):
    return -y + np.sin(t)


def euler(f, y0, t0, tf, h):
    t = np.arange(t0, tf + h, h)
    y = np.zeros(len(t))
    y[0] = y0
    for i in range(len(t) - 1):
        y[i + 1] = y[i] + h * f(t[i], y[i])
    return t, y


# initialize inputs
y0 = 0
t0 = 0
tf = 10
h = 0.1
t, y = euler(example_ODE, y0, t0, tf, h)

# plotting results
plt.plot(t, y, label='Euler method')
plt.xlabel('t')
plt.ylabel('y')
plt.legend()
plt.show()
